[general]
font-sans = "Noto Sans"
font-mono = "GeistMono Nerd Font Mono"

[bar]
scale = 0.800000011920929
module-gap = 1.5
background-opacity = 80
button-variant = "basic"
button-bg-opacity = 0
button-rounding = "md"
button-gap = 1.100000023841858
button-group-background = "transparent"

[[bar.layout]]
monitor = "*"
show = true
left = [
    { name = "Time & Weather", modules = [
    "clock",
    "weather",
] },
    "systray",
    "window-title",
]
center = ["hyprland-workspaces"]
right = [
    { name = "System", modules = [
    "cpu",
    "netstat",
    "ram",
] },
    { name = "Connections", modules = [
    "bluetooth",
    "network",
] },
    { name = "Media", modules = [
    "microphone",
    "volume",
] },
    "battery",
    { name = "Dash", modules = [
    "idle-inhibit",
    "notifications",
    "dashboard",
] },
]

[styling.palette]
bg = "#11111b"
surface = "#181825"
elevated = "#1e1e2e"
fg = "#cdd6f4"
fg-muted = "#bac2de"
primary = "#b4befe"
red = "#f38ba8"
yellow = "#f9e2af"
green = "#a6e3a1"
blue = "#74c7ec"

[modules.bluetooth]
label-show = false

[modules.clock]
format = "%a %d %b %H:%M"

[modules.hyprland-workspaces]
label-use-name = true
divider = "  "
app-icons-show = true
active-indicator = "underline"

[modules.idle-inhibit]
label-show = false

[modules.keybind-mode]
auto-hide = true

[modules.network]
label-show = false

[modules.niri-workspaces]
active-indicator = "underline"

[modules.notifications]
label-show = false
popup-layer = "top"

[modules.weather]
location = "41.46614,12.9043"

[osd]
duration = 1000
layer = "top"

[wallpaper]
cycling-enabled = true
cycling-directory = "/home/lorenzo/Pictures/Wallpapers"
cycling-mode = "shuffle"
