alias ..="cd .."
alias ...="cd ../.."
alias /="cd /"
alias ~="cd ~"
alias reload-zsh="source $ZDOTDIR/.zshrc"
alias zshconfig="${EDITOR:-code} ~/dotfiles"

alias ls="lsd"
alias lla="ls -la"
alias cat="bat"
alias find="fd"
alias grep="ripgrep"
alias rm="trash"
alias top="htop"
eval "$(hub alias -s)"

# Git
alias g="git"
alias ga="git add"
alias gaa="git add --all"
alias gb="git branch"
alias gbd="git branch -d"
alias gc="git commit -v"
alias gc!="git commit -v --amend"
alias gca="git commit -v -a"
alias gcam="git commit -v -a -m"
alias gss="git switch"
alias gsm="git switch master"
alias gsd="git switch develop"
alias gs="git status -sb"
alias gst="git status"
alias gl="git pull"
alias gm="git merge"
alias gma="git merge --abort"
alias gp="git push"
alias grb="git rebase"
alias grba="git rebase --abort"
alias grbc="git rebase --continue"
alias grbd="git rebase develop"
alias grbm="git rebase master"

# Yarn
alias y="yarn"
alias ys="yarn start"
alias yd="yarn dev"
alias yt="yarn test"

# Brew
alias b="brew"
alias bd="brew doctor"
alias bi="brew install"
alias bci="brew cask install"
alias binf="brew info"
alias bs="brew search"
alias bu="brew update"
alias bup="brew upgrade"
alias bo="brew outdated"

# fnm
alias n="fnm"
