import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/alacritty-extra.toml"
]

[env]
term = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
startup_mode = "Maximized"
dynamic_title = false
option_as_alt = "Both"

[font]
size = 12
normal = { family = "GeistMono Nerd Font Mono" }
builtin_box_drawing = false

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "+", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  { key = "/", mods = "Control", chars = "\u001F" },
]
