add_newline = false

format = """\
$time\
$username\
[](fg:#ED8796 bg:#A6DA95)\
$directory\
[](fg:#A6DA95 bg:#EED49F)\
$git_branch\
$git_status\
[](fg:#EED49F bg:#8AADF4)\
$python\
[](fg:#8AADF4)\
$character\
"""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ 󱑍 $time ]($style)'
style = "fg:#24273A bg:#ED8796"

[directory]
format = "[ $path ]($style)"
style = "fg:#24273A bg:#A6DA95"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#24273A bg:#EED49F"

[git_status]
format = '[$all_status ]($style)'
style = "fg:#24273A bg:#EED49F"

[git_metrics]
format = "([+$added ]($added_style))[]($added_style)"
added_style = "fg:#24273A bg:#EED49F"
deleted_style = "fg:#24273A bg:#EED49F"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[ 󱑍 $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[](bold green)'
error_symbol = '[ ✗]()'

[username]
format = '[$user ]($style)'
style_root = "fg:#24273A bg:#ED8796"

[python]
# Show python version and virtual environment name
python_binary = ["python3", "python"]
format = "[ (${virtualenv}) ]($style)"
style = "fg:#24273A bg:#8AADF4"
