-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Sharp Corporation 0x158F",
  mode = "2560x1600@60.00",
  position = "3440x1008",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Xiaomi Corporation Mi Monitor 0000000000000",
  mode = "3440x1440@99.99",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Xiaomi Corporation Mi Monitor 0000000000000", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Xiaomi Corporation Mi Monitor 0000000000000" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Xiaomi Corporation Mi Monitor 0000000000000" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Xiaomi Corporation Mi Monitor 0000000000000" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Xiaomi Corporation Mi Monitor 0000000000000" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Sharp Corporation 0x158F", default = true, persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "desc:Sharp Corporation 0x158F" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Sharp Corporation 0x158F" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Sharp Corporation 0x158F" })
