-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Sharp Corporation 0x158F",
  mode = "2560x1600@120.00",
  position = "3440x1008",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
