#!/usr/bin/env bash

op signin

if [ "$?" == "1" ]; then
	echo '1Password is closed'
	exit 0
fi

dir="$HOME/.config/rofi/launchers/type-2"
theme='style-1-no-icons'

# We don't care about accounts with OAuth login
query=$(cat <<- QUERY
.[] |
select(
	if (.additional_information == null) then
		true
	else
		(.additional_information | startswith("Sign") | not) and
		(.additional_information | startswith("Accedi") | not) and
		(.additional_information | startswith("Google") | not)
	end
) |
	"\(.title) (\(.additional_information))\t|||\(.id)"
QUERY
)

if [ "$?" == "0" ]; then
	result=$(op item list --categories Login --format=json \
		| jq -r "$query" \
		| rofi -async-pre-read 0 -dmenu -i -p "Passwords" -display-columns 1 -theme ${dir}/${theme}.rasi)

	if [ "$?" == "0" ]; then
		id=$(echo $result | awk -F "[|||]+" '{print $2}')

		# xargs trims the string
		name=$(echo $result | awk -F "(" '{print $1}' | xargs)

		pass=$(op item get "$id" --fields label=password)
		wl-copy --trim-newline "$pass"

		notify-send "1Password" "$name copied to clipboard"
	fi
fi

