#!/usr/bin/env bash

dir="$HOME/.config/rofi/launchers/type-2"
theme='style-1-no-icons'

if [ "$?" == "0" ]; then
	result=$(cliphist list \
		| awk -F ' ' '{print $2}' \
		| rofi -async-pre-read 0 -dmenu -i -p "Clipboard" -display-columns 1 -theme ${dir}/${theme}.rasi)

	if [ "$?" == "0" ]; then
		wl-copy --trim-newline "$result"
	fi
fi

