#!/usr/bin/env bash

TEMP=/tmp/term-toggle

exists=$(hyprctl clients | grep term-toggle > /dev/null; echo $?)

show() {
	if [ "$exists" = "1" ]; then
		kitty --class term-toggle --detach
	else
		hyprctl --batch "dispatch focuswindow term-toggle ; dispatch centerwindow"
	fi

	touch $TEMP
}

hide() {
	hyprctl --batch "dispatch movewindowpixel 0 -10000,term-toggle ; dispatch cyclenext prev"
	rm $TEMP
}

if [[ -f $TEMP ]]; then
	# Window is at the center of the screen
	# We need to hide it
	
	# If the program is not running, that means it was closed
	# with the kill signal, it was not hidden
	if [ "$exists" = "1" ]; then
		rm $TEMP
		show
	else
		hide
	fi

else
	# Window is hidden
	# We need to show it
	show
fi
