# vim: ft=hyprlang

exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"

exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = systemctl --user start hyprpolkitagent

exec-once = hypridle
exec-once = nm-applet
exec-once = blueman-applet
exec-once = udiskie
exec-once = kanshi

# exec-once = dunst
# exec-once = $HOME/.config/waybar/waybar-hypr.sh

# exec-once = ashell

# If you enable noctalia-shell, make sure to disable
# ashell, waybar and dunst.
# If you use the noctalia wallpaper handling, you have to
# also disable awww-daemon
exec-once = qs -c noctalia-shell

exec-once = awww-daemon
exec-once = vicinae server
exec-once = 1password --silent
