# vim: ft=hyprlang

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    repeat_delay = 250
    repeat_rate = 70

    follow_mouse = 1
    accel_profile = flat
    sensitivity = 0.5

    touchpad {
        natural_scroll = false
        disable_while_typing = true
        scroll_factor = 0.2
    }
}

device {
  name = at-translated-set-2-keyboard
  kb_options = compose:ralt,caps:swapescape
}

cursor {
  hide_on_key_press = true
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, vertical, workspace
