# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

layerrule {
  name = vicinae-blur
  blur = on
  ignore_alpha = 0
  match:namespace = vicinae
}

layerrule {
  name = vicinae-no-animation
  no_anim = on
  match:namespace = vicinae
}

layerrule = no_anim on, match:namespace waybar

windowrule {
  name = no-screenshare
  match:class = (1password)

  no_screen_share = on
}

windowrule {
  name = float-apps
  match:class = (org.gnome.Nautilus|1password|org.pulseaudio.pavucontrol|blueman-manager|com.gabm.satty)

  float = on
  size = (monitor_w*0.8) (monitor_h*0.7)
}

# windowrule {
#   name = maximised-apps
#   match:class = (helium)
#
#   scrolling_width = 1
# }

windowrule {
  name = quick-terminal
  match:class = (com.ghostty.quick_terminal|quick_terminal|quick-terminal)

  float = on
  size = (monitor_w*0.9) (monitor_h*0.8)
}

windowrule {
  name = picture-in-picture
  match:title = (Picture in picture|Picture in Picture|picture in picture|picture_in_picture|picture-in-picture)

  float = on
  pin = on
  size = (monitor_w*0.4) (monitor_h*0.35)
  move = (monitor_w-(monitor_w*0.4)-12) (monitor_h-(monitor_h*0.35)-12)
}

windowrule {
  name = chat-apps
  match:class = (vesktop|org.telegram.desktop)

  workspace = 6
}

windowrule {
  name = work-chat-apps
  match:class = (slack|teams-for-linux)

  workspace = 5
}

windowrule {
  name = flameshot
  match:class = flameshot

  no_anim = on
  float = on
  pin = on
  move = 0 0
  no_initial_focus = on
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = on
}

layerrule {
  name = wlr-which-key
  match:namespace = wlr_which_key

  animation = popin 87%
}
