add_newline = true
format = "$directory$character"
right_format = "$git_branch$git_status$git_state$line_break"

[character]
error_symbol = "[](bold red)"
success_symbol = "[](bold green)"
vimcmd_replace_one_symbol = "[](bold purple)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_symbol = "[](bold green)"
vimcmd_visual_symbol = "[](bold yellow)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
