[bar.default]
background_opacity = 0.85
center = [ "workspaces" ]
end = [
    "cpu",
    "network_rx",
    "network_tx",
    "ram",
    "bluetooth",
    "network",
    "volume",
    "notifications",
    "battery",
    "screenshot",
    "recorder",
    "wallpaper",
    "caffeine",
    "control-center",
    "session"
]
margin_edge = 0
margin_ends = 0
radius = 0
shadow = false
start = [ "clock", "weather", "tray", "active_window", "media" ]
thickness = 40
widget_spacing = 14

[calendar]
enabled = true

[desktop_widgets]
enabled = false

[dock]
auto_hide = true
enabled = true
icon_size = 36
reserve_space = false

[idle]
behavior_order = [ "Reduce Brightness", "Keyboard Brightness", "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 0

    [idle.behavior."Keyboard Brightness"]
    action = "command"
    command = "kbd_backlight 0"
    enabled = true
    timeout = 180

    [idle.behavior."Reduce Brightness"]
    action = "command"
    command = "brightnessctl -s set 10"
    enabled = true
    timeout = 180

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 400

[location]
address = "Latina, Italia"

[lockscreen]
blurred_desktop = true
fingerprint = false

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-widget-0000000000000001", "lockscreen-login-box@HDMI-A-1", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1600.0
    cy = 900.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.70000000000000007
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 8.0
        show_login_button = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 192.0
    box_width = 416.0
    cx = 1600.0
    cy = 596.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        clock_style = "digital"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 48.0
    box_width = 496.0
    cx = 1600.0
    cy = 708.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        format = "%A %e %B"

[osd.kinds]
bluetooth = false
keyboard_layout = false
media = false
wifi = false

[plugin_settings."noctalia/screen_recorder"]
color_range = "full"
copy_to_clipboard = true

[plugins]
enabled = [ "noctalia/bongocat", "noctalia/screen_recorder" ]

[shell]
clipboard_enabled = false
font_family = "GeistMono NF"
launch_apps_as_systemd_services = true
polkit_agent = true
settings_show_advanced = true

    [shell.panel]
    session_placement = "centered"
    wallpaper_placement = "floating"

    [shell.screenshot]
    copy_to_clipboard = false
    directory = "~/Pictures/Screenshots"
    pipe_command = "satty -f -"
    pipe_to_command = true
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "o"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = true
    shortcut = "u"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    command = "hyprshutdown -t 'Restarting...' --post-cmd 'reboot'"
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    command = "hyprshutdown -t 'Shutting down...' --post-cmd 'shutdown -P 0'"
    enabled = true
    shortcut = "s"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.19999999552965164

[theme]
builtin = "Catppuccin"
community_palette = "Oxocarbon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "~/Pictures/Wallpapers"

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/lorenzo/Pictures/Wallpapers/tyler-durden-zm.jpg"

    [wallpaper.last]
    path = "/home/lorenzo/Pictures/Wallpapers/tyler-durden-zm.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/lorenzo/Pictures/Wallpapers/tyler-durden-zm.jpg"

    [[wallpaper.favorite]]
    builtin_palette = "Catppuccin"
    palette_source = "builtin"
    path = "/home/lorenzo/Pictures/Wallpapers/0078.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    path = "/home/lorenzo/Pictures/Wallpapers/1123121.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    builtin_palette = "Catppuccin"
    palette_source = "builtin"
    path = "/home/lorenzo/Pictures/Wallpapers/2897748.jpg"
    theme_mode = "dark"

[widget.active_window]
max_length = 180
title_scroll = "on_hover"

[widget.battery]
display_mode = "graphic"

[widget.cat]
type = "noctalia/bongocat:cat"

[widget.clock]
format = "%a %e %b %H:%M"

[widget.cpu]
show_label = false

[widget.media]
hide_when_no_media = true
max_length = 180
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.network_rx]
show_label = false

[widget.network_tx]
show_label = false

[widget.ram]
show_label = false
stat = "ram_pct"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.weather]
show_condition = false

[widget.workspaces]
display = "name"
empty_color = "primary"
focused_color = "tertiary"
hide_when_empty = true
occupied_color = "primary"
