[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
decorations = "None"
option_as_alt = "OnlyLeft"

[font]
normal = { family = "GeistMono Nerd Font Mono", style = "Regular"}
