[general]
import = [
  "~/.config/alacritty/themes/current.toml"
]

[window]
decorations = "None"
option_as_alt = "OnlyLeft"

[font]
normal = { family = "GeistMono Nerd Font Mono", style = "Regular"}

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
